// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3r0-gFEZE29ipb2nUZmI4FSW23sxtABQ',
    appId: '1:976766461144:android:2279b350a9a404bba1e3ad',
    messagingSenderId: '976766461144',
    projectId: 'pesca-huka',
    storageBucket: 'pesca-huka.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_JOE8O-RpXOpic5hi57mGFIjLBkG8JWs',
    appId: '1:976766461144:ios:358b36fe6cb812eea1e3ad',
    messagingSenderId: '976766461144',
    projectId: 'pesca-huka',
    storageBucket: 'pesca-huka.firebasestorage.app',
    androidClientId: '976766461144-ogn3d3dde2vg21scb7atb672pf88ths5.apps.googleusercontent.com',
    iosClientId: '976766461144-fpacsm925nlvc26ht9bdh6dfll0casck.apps.googleusercontent.com',
    iosBundleId: 'com.example.jukaFlutter',
  );
}
